export const OFFER_RNG_SEED_SALT = 0x6d2b79f5;

export const UPGRADE_CATALOG = [
  {
    id: "wide_slash",
    kind: "skill",
    label: "Wide Slash",
    description: "Increase slash arc width.",
    maxRank: 2,
    requires: [],
    excludes: ["quick_slash"],
    tags: ["skill", "melee", "arc"],
    effect: { kind: "attackArc", amount: 0.18 },
  },
  {
    id: "quick_slash",
    kind: "skill",
    label: "Quick Slash",
    description: "Reduce attack cooldown between swings.",
    maxRank: 2,
    requires: [],
    excludes: ["wide_slash"],
    tags: ["skill", "melee", "cooldown"],
    effect: { kind: "attackCooldown", amount: -0.04 },
  },
  {
    id: "edge_control",
    kind: "skill",
    label: "Edge Control",
    description: "Extend slash reach slightly.",
    maxRank: 1,
    requires: [],
    excludes: [],
    tags: ["skill", "melee", "range"],
    effect: { kind: "attackRadius", amount: 0.22 },
  },
  {
    id: "arc_bloom",
    kind: "skill",
    label: "Arc Bloom",
    description: "Further bloom slash arc after Wide Slash.",
    maxRank: 2,
    requires: ["wide_slash"],
    excludes: ["quick_slash"],
    tags: ["skill", "melee", "arc"],
    effect: { kind: "attackArc", amount: 0.16 },
  },
  {
    id: "heavy_hand",
    kind: "talent",
    label: "Heavy Hand",
    description: "Increase attack damage.",
    maxRank: 3,
    requires: [],
    excludes: [],
    tags: ["talent", "offense"],
    effect: { kind: "attackDamage", amount: 2 },
  },
  {
    id: "sturdy_frame",
    kind: "talent",
    label: "Sturdy Frame",
    description: "Increase maximum health.",
    maxRank: 2,
    requires: [],
    excludes: [],
    tags: ["talent", "defense"],
    effect: { kind: "maxHp", amount: 12 },
  },
  {
    id: "swift_step",
    kind: "talent",
    label: "Swift Step",
    description: "Increase movement speed.",
    maxRank: 2,
    requires: [],
    excludes: [],
    tags: ["talent", "mobility"],
    effect: { kind: "moveSpeed", amount: 0.35 },
  },
  {
    id: "battle_tempo",
    kind: "talent",
    label: "Battle Tempo",
    description: "Convert quick swings into steady damage pressure.",
    maxRank: 1,
    requires: ["quick_slash"],
    excludes: ["wide_slash"],
    tags: ["talent", "tempo"],
    effect: { kind: "attackDamage", amount: 1 },
  },
];
